#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot picom
#picom --experimental-backends --backend glx -b &
picom &
fcitx -d &

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#set background
feh --no-fehbg --bg-center '/home/pan/Pictures/bg2.png' '/home/pan/Pictures/bg1.png' &

#boot lemonbar and pipe the status of left into it
sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d') )

index=0
for size in "${sizes[@]}"
do
   leftwm-state -w $index -t $SCRIPTPATH/template.liquid | lemonbar -g $size -F#FFA9B1D6 -B#E0282E4A -f"azuki_font" &
   let index=index+1
done
