#!/bin/sh

picom &
dunst &
fcitx -d &
sxhkd -c '/home/pan/.config/sxhkd/sxhkdrc.bspwm' &
~/.config/polybar/bspwm.sh &
feh --no-fehbg --bg-center '/home/pan/med/pix/bg3.png' '/home/pan/med/pix/bg3.png' &
btops &
stack-layout &

export _JAVA_AWT_WM_NONREPARENTING=1

# Workspace Settings

bspc config split_ratio       0.75
bspc config automatic_scheme  longest_side

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

# Styling

bspc config border_width  2
bspc config window_gap    3

bspc config normal_border_color   "#1E1D2F"
bspc config active_border_color   "#1E1D2F"
bspc config focused_border_color  "#F5C2E7"

# reset rules
bspc rule -r *

# Window Rules

bspc rule -a discord desktop="💬 CHT"
bspc rule -a dgg-chat desktop="💬 CHT"
bspc rule -a Signal desktop="💬 CHT"
bspc rule -a Mumble desktop="💬 CHT"

bspc rule -a librewolf desktop="🌐 WEB"

bspc rule -a obsidian desktop="🗒️N NTE"
bspc rule -a Zathura desktop="🗒️ N NTE"

bspc rule -a Steam desktop="🎲 GME"
bspc rule -a lutris desktop="🎲 GME"

bspc rule -a 'leagueclientux.exe' desktop="💀 LOL" state=pseudo_tiled

bspc rule -a gdlauncher desktop="⛏️  MC" state=floating

bspc rule -a zoom desktop="📸 VID" state=floating center=on follow=on

bspc rule -a Spotify desktop="🎧 MUS"

bspc rule -a mpv desktop="👀 VID"
